title: "내 블로그"
description: "연구 기록 및 글 모음"
baseurl: "" # 프로젝트 전용이면 "/repo-name"
url: "https://wherolee.github.io"

author:
  name: "Whero Lee"
  bio: "연구자 · 개발자 · 블로거"
  location: "Seoul, Korea"

theme: minimal-mistakes-jekyll

plugins:
  - jekyll-feed
  - jekyll-seo-tag

markdown: kramdown
highlighter: rouge

paginate: 5
paginate_path: "/page:num/"
