baseURL = 'https://wheroLee.github.io/'
languageCode = "en-us"
title = '내 Hugo 블로그'
theme = 'PaperMod'
copyright = "© wherolee"
# Code Highlight
pygmentsstyle = "monokai"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

disqusShortname = "wherolee"

paginate=10 # articles per page

[params]
  author = "Whero Lee"
  description = "연구 기록과 생각을 공유하는 블로그"
  defaultTheme = "auto"
  ShowReadingTime = true
  ShowShareButtons = true
  ShowCodeCopyButtons = true
  
	mode="toggle" # color-mode → light,dark,toggle or auto
	useCDN=false # don't use CDNs for fonts and icons, instead serve them locally.
	subtitle = "WheroLee world blog with hugo Archie template"
	mathjax = true # enable MathJax support
	katex = true # enable KaTeX support

# Social Tags

[[params.social]]
name = "GitHub"
icon = "github"
url = "https://github.com/hwantage"

#[[params.social]]
#name = "Twitter"
#icon = "twitter"
#url = "https://twitter.com/athulcajay/"

#[[params.social]]
#name = "GitLab"
#icon = "gitlab"
#url = "https://gitlab.com/athul/"

# Main menu Items

[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "All posts"
url = "/posts"
weight = 2

[[menu.main]]
name = "About"
url = "/about"
weight = 3

[[menu.main]]
name = "Tags"
url = "/tags"
weight = 4
