baseURL = "https://wherolee.github.io/"
publishDir = "public"
languageCode = "en-us"
title = "Hugo Site Sine 2025"
theme = "PaperMod"

relativeURLs = true
canonifyURLs = true
# ------------------------
# 메뉴 설정
# ------------------------
[menu]
  [[menu.main]]
    name = "Home"
    url = "/"
    weight = 1

  [[menu.main]]
    name = "About"
    url = "/about/"
    weight = 2

  [[menu.main]]
    name = "Categories"
    url = "/categories/"
    weight = 3

  [[menu.main]]
    name = "Tags"
    url = "/tags/"
    weight = 4

  [[menu.main]]
    name = "Archive"
    url = "/archives/"
    weight = 5

[outputs]
  home = ["HTML", "RSS"]

# ------------------------
# 사이트 파라미터
# ------------------------
[params]
#  fontMain = "Inter, sans-serif"
  fontMain = "Fira Code, monospace"
  fontMono = "Fira Code, monospace"
  fontSize = "18px"
  lineHeight = 1.8
  customCSS = ["css/custom.css"]
  themeColor = "#1e90ff"
  accentColor = "#ff6347"
  darkTheme = true
  enableSearch = true

# ------------------------
# 사이드바 설정
# ------------------------
[params.sidebar]
  showSidebar = true
  showRecent = true
  recentTitle = "최근 글"
  recentCount = 5
  showTags = true
  tagsTitle = "태그"

# ------------------------
# 소셜 링크
# ------------------------
[params.social]
  github = "https://github.com/wheroLee"
  linkedin = "https://www.linkedin.com/in/wheroLee/"
