name: Hugo Deploy
on:
  push:
    branches:
      - page_with_Hugo   # or "main" if that's your main branch
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write   # 👈 ensures bot can push
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: true
          fetch-depth: 0

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v3.0.0
        with:
          hugo-version: 'latest'
          extended: true

      - name: Build
        run: hugo --minify

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v4.0.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
          publish_branch: gh-pages
